[package]
name = "blackjack"
version = "0.1.0"
authors = ["Marco Fantoli"]
edition = "2021"
description = "Simple blackjack implementation in Rust"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="*"